package com.domi.support.utils;


//Generated by MyEclipse
public interface IJYWebservice {

	public String compareAll(String strName, String strId, String strIDPhoto,
			String strData, String strTime, String strLicenseCode1,
			String strEncryValue1, String strLicenseCode2,
			String strEncryValue2, String strLicenseCode3, String strEncryValue3)
			throws Exception;
	public String compare(String strName, String strId, String strPhoto1,
			String strPhoto2, String strTime, String strLicenseCode,
			String strEncryValue) throws Exception;
}